# Generated by Django 4.2.11 on 2024-05-10 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_protocol_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(1.0)],
                verbose_name="Payment net price",
            ),
        ),
    ]
