# Generated by Django 4.2.6 on 2023-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_name", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=50)),
                ("postcode", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=50)),
            ],
        ),
    ]
