# Generated by Django 4.2.6 on 2023-11-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("krs", models.BigIntegerField()),
                ("regon", models.BigIntegerField()),
                ("nip", models.BigIntegerField()),
                ("is_mine", models.BooleanField(default=False)),
                (
                    "address",
                    models.ForeignKey(
                        default="SET ADDRESS",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="dashboards.address",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
    ]
