# Generated by Django 4.2.6 on 2023-11-20 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_alter_address_options_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dashboards.address",
            ),
        ),
    ]
