# Generated by Django 4.2.6 on 2023-11-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0003_alter_company_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboards.address",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="krs",
            field=models.BigIntegerField(verbose_name="KRS Number"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="nip",
            field=models.BigIntegerField(verbose_name="NIP Number"),
        ),
        migrations.AlterField(
            model_name="company",
            name="regon",
            field=models.BigIntegerField(verbose_name="REGON Number"),
        ),
    ]
