# Generated by Django 4.2.6 on 2023-11-22 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0004_alter_company_address_alter_company_krs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="address",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
