# Generated by Django 4.2.11 on 2024-05-08 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("employment contract", "employment contract"),
                            ("commission agreement", "commission agreement"),
                            ("contract of mandate", "contract of mandate"),
                            ("B2B", "B2B"),
                        ],
                        max_length=20,
                    ),
                ),
                ("salary_gross", models.IntegerField()),
                ("create_date", models.DateField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(help_text="Date in agreement scan.")),
                (
                    "end_date_actual",
                    models.DateField(
                        help_text="Calculated date after adding addenda or termination. Necessary to calculate vacations for employee."
                    ),
                ),
                ("scan", models.FileField(upload_to="agreements")),
                ("is_current", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vacation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("annual", "annual"),
                            ("maternity", "maternity"),
                            ("parental", "parental"),
                            ("childcare", "childcare"),
                            ("special", "special"),
                            ("sick", "sick"),
                            ("unpaid", "unpaid"),
                        ],
                        max_length=9,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("scan", models.FileField(upload_to="vacations")),
                (
                    "included_days_off",
                    models.PositiveSmallIntegerField(
                        help_text="If you take vacations and there are included days off (for example weekend) then you set included_days_off as 2 to count properly."
                    ),
                ),
                (
                    "leave_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("substitute_users", models.ManyToManyField(related_name="vacation", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Termination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                ("create_date", models.DateField()),
                ("end_date", models.DateField()),
                ("scan", models.FileField(upload_to="terminations/")),
                (
                    "agreement",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="employees.agreement"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("fee", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Salaries",
            },
        ),
        migrations.CreateModel(
            name="Addendum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                ("create_date", models.DateField()),
                ("end_date", models.DateField()),
                ("salary_gross", models.IntegerField()),
                ("scan", models.FileField(upload_to="addenda")),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="addenda", to="employees.agreement"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addenda",
            },
        ),
    ]
