# Generated by Django 4.2.11 on 2024-07-16 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacation",
            name="leave_user",
            field=models.ForeignKey(
                help_text="Employee which is going on vacation.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vacation",
            name="substitute_users",
            field=models.ManyToManyField(
                help_text="Employees which will substitute the employee on vacation.",
                related_name="vacation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="termination",
            name="agreement",
            field=models.OneToOneField(
                help_text="Agreement to which the termination relates.",
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.agreement",
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="user",
            field=models.ForeignKey(
                help_text="The money went to this employee.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="user",
            field=models.ForeignKey(
                help_text="The employee concerned by the agreement.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="addendum",
            name="agreement",
            field=models.ForeignKey(
                help_text="Agreement to which the addendum relates.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addenda",
                to="employees.agreement",
            ),
        ),
    ]
