# Generated by Django 5.0.1 on 2024-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addendum",
            name="salary_gross",
            field=models.IntegerField(),
        ),
    ]
