# Generated by Django 4.2.14 on 2024-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="end_date_actual",
            field=models.DateField(
                help_text="Calculated last day of the agreement after adding addenda or termination.Necessary to calculate vacations for employee."
            ),
        ),
    ]
