# Generated by Django 4.2.10 on 2024-02-27 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0003_alter_addendum_agreement_alter_vacation_leave_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacation",
            name="substitute_users",
            field=models.ManyToManyField(
                related_name="vacation", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
