# Generated by Django 5.0.1 on 2024-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_addendum_salary_gross"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacation",
            name="days_off",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agreement",
            name="end_date",
            field=models.DateField(help_text="Date in agreement scan."),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="end_date_actual",
            field=models.DateField(
                help_text="Calculated date after adding addenda or termination. Necessary to calculate vacations for employee."
            ),
        ),
    ]
