# Generated by Django 5.0.1 on 2024-02-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_alter_agreement_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacation",
            name="included_days_off",
            field=models.PositiveSmallIntegerField(
                help_text="If you take vacations and there are included days off (for example weekend) then you set included_days_off as 2."
            ),
        ),
    ]
