# Generated by Django 4.2.14 on 2024-08-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("street_name", models.CharField(help_text="Street name e.g. Warszawska", max_length=100)),
                (
                    "street_number",
                    models.CharField(help_text="Building number/apartment number e.g. 21/37", max_length=10),
                ),
                ("city", models.CharField(help_text="City e.g. Warsaw", max_length=100)),
                ("postcode", models.CharField(help_text="Postcode e.g. 01-234", max_length=10)),
                ("country", models.CharField(help_text="Country e.g. Poland", max_length=100)),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Company name e.g. PLUS SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",
                        max_length=100,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "krs",
                    models.BigIntegerField(
                        help_text="Identifier of company. It's 9 (if company is based in one voivodeship) or 14 (if more than one voivodeship) digits.",
                        unique=True,
                        verbose_name="KRS Number",
                    ),
                ),
                (
                    "regon",
                    models.BigIntegerField(
                        help_text="Identifier of company. It's 9 digits.", unique=True, verbose_name="REGON Number"
                    ),
                ),
                (
                    "nip",
                    models.BigIntegerField(
                        help_text="Identifier of company. It's 10 digits.", unique=True, verbose_name="NIP Number"
                    ),
                ),
                (
                    "is_mine",
                    models.BooleanField(
                        blank=True, default=False, help_text="Set true if this company is yours, set false if it's not."
                    ),
                ),
                (
                    "shortcut",
                    models.CharField(
                        help_text="Shortcut of the name of the company, e.g. PLUS", max_length=5, unique=True
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        help_text="Address where company is registered in KRS system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.address",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="It's person full name, e.g. John Doe", max_length=100)),
                ("email", models.EmailField(blank=True, help_text="Email, e.g. john_doe@gmail.com", max_length=100)),
                ("phone", models.CharField(blank=True, help_text="Phone number, e.g. +48123456789", max_length=25)),
                (
                    "description",
                    models.CharField(
                        help_text="Description of that person, e.g. position in the company, special signs - generally less or more important information.",
                        max_length=200,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company for which the contact person works.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "email", "phone", "company")},
            },
        ),
    ]
