# Generated by Django 4.2.11 on 2024-07-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(help_text="City e.g. Warsaw", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(help_text="Country e.g. Poland", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="postcode",
            field=models.CharField(help_text="Postcode e.g. 01-234", max_length=10),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_name",
            field=models.CharField(help_text="Street name e.g. Warszawska", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_number",
            field=models.CharField(help_text="Building number/apartment number e.g. 21/37", max_length=10),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.ForeignKey(
                help_text="Address where company is registered in KRS system.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.address",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_mine",
            field=models.BooleanField(
                blank=True, default=False, help_text="Set true if this company is yours, set false if it's not."
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="krs",
            field=models.BigIntegerField(
                help_text="Identifier of company. It's 9 (if company is based in one voivodeship) or 14 (if more than one voivodeship) digits.",
                unique=True,
                verbose_name="KRS Number",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Company name e.g. PLUS SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",
                max_length=100,
                verbose_name="Company Name",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="nip",
            field=models.BigIntegerField(
                help_text="Identifier of company. It's 10 digits.", unique=True, verbose_name="NIP Number"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="regon",
            field=models.BigIntegerField(
                help_text="Identifier of company. It's 9 digits.", unique=True, verbose_name="REGON Number"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="shortcut",
            field=models.CharField(
                help_text="Shortcut of the name of the company, e.g. PLUS", max_length=5, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                help_text="The company for which the contact person works.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="description",
            field=models.CharField(
                help_text="Description of that person, e.g. position in the company, special signs - generally less or more important information.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, help_text="Email, e.g. john_doe@gmail.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(help_text="It's person full name, e.g. John Doe", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, help_text="Phone number, e.g. +48123456789", max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("street_name", "street_number", "city", "postcode", "country")},
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("name", "email", "phone", "company")},
        ),
    ]
