# Generated by Django 5.0.1 on 2024-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="is_mine",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
