# Generated by Django 4.2.11 on 2024-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="krs",
            field=models.BigIntegerField(unique=True, verbose_name="KRS Number"),
        ),
        migrations.AlterField(
            model_name="company",
            name="nip",
            field=models.BigIntegerField(unique=True, verbose_name="NIP Number"),
        ),
        migrations.AlterField(
            model_name="company",
            name="regon",
            field=models.BigIntegerField(unique=True, verbose_name="REGON Number"),
        ),
    ]
