# Generated by Django 4.2.11 on 2024-05-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_alter_company_krs_alter_company_nip_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("street_name", "street_number", "city", "postcode", "country")},
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("name", "email", "phone", "company")},
        ),
    ]
