# Generated by Django 5.0.1 on 2024-02-05 15:57

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("companies", "0002_alter_company_is_mine"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("phone_number", models.CharField(max_length=50, null=True)),
                ("position", models.CharField(max_length=30, null=True)),
                (
                    "vacation_days_per_year",
                    models.PositiveSmallIntegerField(default=26),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="photos/undraw_profile.svg", upload_to="photos"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.address",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "swappable": "AUTH_USER_MODEL",
            },
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("employment contract", "employment contract"),
                            ("commission agreement", "commission agreement"),
                            ("contract of mandate", "contract of mandate"),
                            ("B2B", "B2B"),
                        ],
                        max_length=20,
                    ),
                ),
                ("salary_gross", models.PositiveSmallIntegerField()),
                ("create_date", models.DateField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("end_date_actual", models.DateField()),
                ("scan", models.FileField(upload_to="agreements")),
                ("is_current", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Addendum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("create_date", models.DateField()),
                ("end_date", models.DateField()),
                ("salary_gross", models.PositiveSmallIntegerField()),
                ("scan", models.FileField(upload_to="addenda")),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.agreement",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addenda",
            },
        ),
        migrations.CreateModel(
            name="Termination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("create_date", models.DateField()),
                ("end_date", models.DateField()),
                ("scan", models.FileField(upload_to="terminations/")),
                (
                    "agreement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.agreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("annual", "annual"),
                            ("maternity", "maternity"),
                            ("parental", "parental"),
                            ("childcare", "childcare"),
                            ("special", "special"),
                            ("sick", "sick"),
                            ("unpaid", "unpaid"),
                        ],
                        max_length=9,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("scan", models.FileField(upload_to="vacations")),
                (
                    "leave_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "substitute_users",
                    models.ManyToManyField(
                        related_name="substitute_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
