# Generated by Django 5.0.1 on 2024-02-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="vacation_left",
            field=models.SmallIntegerField(default=0),
        ),
    ]
