# Generated by Django 5.0.1 on 2024-02-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vacation_left",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
