# Generated by Django 5.0.1 on 2024-02-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_vacation_left"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agreement",
            name="user",
        ),
        migrations.RemoveField(
            model_name="termination",
            name="agreement",
        ),
        migrations.RemoveField(
            model_name="vacation",
            name="leave_user",
        ),
        migrations.RemoveField(
            model_name="vacation",
            name="substitute_users",
        ),
        migrations.DeleteModel(
            name="Addendum",
        ),
        migrations.DeleteModel(
            name="Agreement",
        ),
        migrations.DeleteModel(
            name="Termination",
        ),
        migrations.DeleteModel(
            name="Vacation",
        ),
    ]
