# Generated by Django 4.2.14 on 2024-08-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Contract name, e.g. Contract #PLAY-01/01/2024", max_length=25)),
                ("create_date", models.DateField(help_text="Creation date of the contract.")),
                ("start_date", models.DateField(help_text="First day of the contract.")),
                ("end_date", models.DateField(help_text="Last day of the contract.")),
                ("price", models.PositiveIntegerField(help_text="The whole net income from the contract.")),
                ("scan", models.FileField(help_text="The physical version of the contract.", upload_to="contracts/")),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company concerned by the contract.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
