# Generated by Django 4.2.10 on 2024-03-18 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="employee",
            field=models.ManyToManyField(related_name="contracts", to=settings.AUTH_USER_MODEL),
        ),
    ]
