# Generated by Django 4.2.11 on 2024-05-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_address_unique_together_and_more"),
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("name", "create_date", "start_date", "end_date", "company", "price")},
        ),
    ]
